-- 테이블등록
CREATE TABLE MEMBERS (
	MNO      INTEGER      NOT NULL, -- 회원일련번호
	EMAIL    VARCHAR2(40)  NOT NULL, -- 이메일
	PWD      VARCHAR2(100) NOT NULL, -- 암호
	MNAME    VARCHAR2(50)  NOT NULL, -- 이름
	CRE_DATE DATE     NOT NULL, -- 가입일
	MOD_DATE DATE     NOT NULL -- 마지막암호변경일
)
;

-- 코멘트
COMMENT ON TABLE MEMBERS IS '회원기본';
COMMENT ON COLUMN MEMBERS.MNO IS '회원일련번호';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.PWD IS '암호';
COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '가입일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '마지막암호변경일';

-- PK설정
ALTER TABLE MEMBERS ADD CONSTRAINT PK_MEMBERS PRIMARY KEY (MNO);

-- 유니크 인덱스
CREATE UNIQUE INDEX UIX_MEMBERS ON MEMBERS (EMAIL ASC);

-- 시쿼스 생성
CREATE SEQUENCE MEMBERS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 9999 NOCYCLE NOCACHE;

-- 데이터 입력
INSERT INTO MEMBERS(MNO, EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE)
VALUES (MEMBERS_SEQ.NEXTVAL, 's1@test.com','1111','홍길동',SYSDATE,SYSDATE);

INSERT INTO MEMBERS(MNO, EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE)
VALUES (MEMBERS_SEQ.NEXTVAL, 's2@test.com','1111','임꺽정',SYSDATE,SYSDATE);

INSERT INTO MEMBERS(MNO, EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE)
VALUES (MEMBERS_SEQ.NEXTVAL, 's3@test.com','1111','일지매',SYSDATE,SYSDATE);

INSERT INTO MEMBERS(MNO, EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE)
VALUES (MEMBERS_SEQ.NEXTVAL, 's4@test.com','1111','이몽룡',SYSDATE,SYSDATE);

INSERT INTO MEMBERS(MNO, EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE)
VALUES (MEMBERS_SEQ.NEXTVAL, 's5@test.com','1111','성춘향',SYSDATE,SYSDATE);

SELECT * FROM MEMBERS;
